name: Nightly Release

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * 1-5"

jobs:
  fedora:
    name: Linux Fedora (Release, GCC, cxx11)
    runs-on: ubuntu-latest
    container: dynawo/dynawo-distribution-cxx11:latest
    strategy:
      fail-fast: false
    env:
      DYNAWO_INSTALL_OPENMODELICA: /opt/OpenModelica/Install
      DYNAWO_SRC_OPENMODELICA: /opt/OpenModelica/Source
      DYNAWO_RESULTS_SHOW: "false"
      DYNAWO_BUILD_TYPE: Release
      DYNAWO_CXX11_ENABLED: YES
      DYNAWO_NB_PROCESSORS_USED: 2
      DYNAWO_FORCE_CXX11_ABI: "true"
      VERSION: "1.3.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Dynawo
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "sheosi/dynawo"
          version: "tags/nightly"
          file: "Dynawo_headers_V${{ env.VERSION }}"
          target: "dynawo/dynawo.zip"
          token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Extract Dynawo
        run: |
          cd dynawo
          unzip -qq "dynawo.zip"
          cd ..

      - name: Build
        run: |
          export DYNAWO_HOME=$(pwd)/dynawo
          export DYNAWO_ALGORITHMS_HOME=$(pwd)
          util/envDynawoAlgorithms.sh build
      
      - name: Prepare files
        run: |
          export DYNAWO_HOME=$(pwd)/dynawo
          export DYNAWO_ALGORITHMS_HOME=$(pwd)
          util/envDynawoAlgorithms.sh distrib-headers

      - name: Delete old tag and release
        run: |
          curl -sw '%{http_code}\n' --header "Content-Type": " application/json" -u "user:${{ secrets.GITHUB_TOKEN }}" -X DELETE  "https://api.github.com/repos/sheosi/dynawo/git/refs/tags/nightly"

      - name: Get last commit in master
        id: commit_id
        run: |
          echo "::set-output name=MASTER_COMMIT_ID::$(curl -s --header 'Content-Type': 'application/json' -X GET  'https://api.github.com/repos/sheosi/dynawo/git/refs/heads/master'| python3 -c 'import sys, json; print(json.load(sys.stdin)["object"]["sha"])')"

      - name: Create Nightly Tag
        run: |
          curl -X POST -d '{"ref":"refs/tags/nightly","sha":"${{ steps.commit_id.outputs.MASTER_COMMIT_ID }}"}' --header "Content-Type:application/json" -u "user:${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/sheosi/dynawo/git/refs"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: "Nightly"
          body: "Dynwo algorithms's nightly release. Compiled on *release* settings.\n\n **Don't use it for production**"
          commit: "master"
          tag: "${{ steps.commit_id.outputs.MASTER_COMMIT_ID }}"
          artifacts: "distributions/*"
          allowUpdates: true
          prerelease: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
